ip route 192.0.2.32/28 blackhole
!
router bgp 65000
 bgp router-id 10.255.0.7
 neighbor RR peer-group
 neighbor RR remote-as 65000
 neighbor RR update-source 10.255.0.7
 neighbor RR timers connect 5
 neighbor 10.255.0.11 peer-group RR
 neighbor 10.255.0.12 peer-group RR
 address-family ipv4 unicast
  network 192.0.2.32/28
 exit-address-family
exit
!
