router bgp 65000
 bgp router-id 10.255.0.11
 neighbor CLIENTS peer-group
 neighbor CLIENTS remote-as 65000
 neighbor CLIENTS update-source 10.255.0.11
 neighbor CLIENTS timers connect 5
 neighbor 10.255.0.1 peer-group CLIENTS
 neighbor 10.255.0.2 peer-group CLIENTS
 neighbor 10.255.0.3 peer-group CLIENTS
 neighbor 10.255.0.4 peer-group CLIENTS
 neighbor 10.255.0.5 peer-group CLIENTS
 neighbor 10.255.0.6 peer-group CLIENTS
 neighbor 10.255.0.7 peer-group CLIENTS
 neighbor 10.255.0.8 peer-group CLIENTS
 neighbor 10.255.0.9 peer-group CLIENTS
 neighbor 10.255.0.12 remote-as 65000
 neighbor 10.255.0.12 update-source 10.255.0.11
 neighbor 10.255.0.12 timers connect 5
 address-family ipv4 unicast
  neighbor CLIENTS route-reflector-client
 exit-address-family
exit
!
