frr defaults traditional
hostname arelion
service integrated-vtysh-config
!
interface eth1
 ip address 10.100.1.1/31
exit
!
interface eth2
 ip address 10.100.3.0/31
exit
!
router bgp 65101
 bgp router-id 10.100.1.1
 no bgp ebgp-requires-policy
 neighbor 10.100.1.0 remote-as 65000
 neighbor 10.100.1.0 timers connect 5
 neighbor 10.100.3.1 remote-as 65200
 neighbor 10.100.3.1 timers connect 5
exit
!
