frr defaults traditional
hostname bologna
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.4/32
 ip ospf area 0
 ip ospf passive
!
interface eth1
 ip address 10.0.0.5/31
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.0.6/31
 ip ospf area 0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.4
!
line vty
!
