frr defaults traditional
hostname br2
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.0.15/31
 ip router isis CORE
 isis network point-to-point
exit
!
interface eth2
 description COGENT
 ip address 10.100.2.0/31
exit
!
interface lo
 ip address 10.255.0.6/32
 ip router isis CORE
 isis passive
exit
!
ip route 192.0.2.0/24 blackhole
!
ip prefix-list OUR-PREFIXES seq 10 permit 192.0.2.0/24
!
route-map UPSTREAM-IN permit 10
exit
!
route-map UPSTREAM-OUT permit 10
 match ip address prefix-list OUR-PREFIXES
exit
!
router isis CORE
 is-type level-2-only
 net 49.0001.0102.5500.0006.00
 lsp-gen-interval 1
 spf-interval 1
exit
!
router bgp 65000
 bgp router-id 10.255.0.6
 neighbor RR peer-group
 neighbor RR remote-as 65000
 neighbor RR update-source 10.255.0.6
 neighbor RR timers connect 5
 neighbor 10.255.0.11 peer-group RR
 neighbor 10.255.0.12 peer-group RR
 neighbor 10.100.2.1 remote-as 65102
 neighbor 10.100.2.1 description COGENT
 neighbor 10.100.2.1 timers connect 5
 !
 address-family ipv4 unicast
  network 192.0.2.0/24
  neighbor RR activate
  neighbor RR next-hop-self
  neighbor 10.100.2.1 activate
  neighbor 10.100.2.1 route-map UPSTREAM-IN in
  neighbor 10.100.2.1 route-map UPSTREAM-OUT out
 exit-address-family
exit
!
