!
frr version 10.2.1_git
frr defaults traditional
hostname br2
no ipv6 forwarding
service integrated-vtysh-config
!
ip prefix-list OUR-PREFIXES seq 10 permit 192.0.2.0/24
ip prefix-list BOGONS seq 5 permit 0.0.0.0/8 le 32
ip prefix-list BOGONS seq 10 permit 10.0.0.0/8 le 32
ip prefix-list BOGONS seq 15 permit 100.64.0.0/10 le 32
ip prefix-list BOGONS seq 20 permit 127.0.0.0/8 le 32
ip prefix-list BOGONS seq 25 permit 169.254.0.0/16 le 32
ip prefix-list BOGONS seq 30 permit 172.16.0.0/12 le 32
ip prefix-list BOGONS seq 35 permit 192.168.0.0/16 le 32
ip prefix-list BOGONS seq 40 permit 224.0.0.0/3 le 32
ip prefix-list BOGONS seq 45 permit 0.0.0.0/0
ip prefix-list BOGONS seq 50 permit 0.0.0.0/0 ge 25
ip prefix-list OUR-SPACE seq 5 permit 192.0.2.0/24 le 32
!
ip route 192.0.2.0/24 blackhole
!
interface eth1
 ip address 10.0.0.15/31
 ip router isis CORE
 isis network point-to-point
exit
!
interface eth2
 description COGENT
 ip address 10.100.2.0/31
exit
!
interface lo
 ip address 10.255.0.6/32
 ip router isis CORE
 isis passive
exit
!
router bgp 65000
 bgp router-id 10.255.0.6
 neighbor RR peer-group
 neighbor RR remote-as 65000
 neighbor RR update-source 10.255.0.6
 neighbor RR timers connect 5
 neighbor 10.255.0.11 peer-group RR
 neighbor 10.255.0.12 peer-group RR
 neighbor 10.100.2.1 remote-as 65102
 neighbor 10.100.2.1 description COGENT
 neighbor 10.100.2.1 timers connect 5
 !
 address-family ipv4 unicast
  network 192.0.2.0/24
  neighbor RR next-hop-self
  neighbor 10.100.2.1 soft-reconfiguration inbound
  neighbor 10.100.2.1 maximum-prefix 100 80 restart 5
  neighbor 10.100.2.1 route-map UPSTREAM-IN in
  neighbor 10.100.2.1 route-map UPSTREAM-OUT out
 exit-address-family
exit
!
router isis CORE
 is-type level-2-only
 net 49.0001.0102.5500.0006.00
 lsp-timers gen-interval 1 refresh-interval 900 max-lifetime 1200
exit
!
route-map UPSTREAM-IN deny 5
 match ip address prefix-list BOGONS
exit
!
route-map UPSTREAM-IN deny 6
 match ip address prefix-list OUR-SPACE
exit
!
route-map UPSTREAM-IN permit 10
 set local-preference 100
exit
!
route-map UPSTREAM-OUT permit 10
 match ip address prefix-list OUR-PREFIXES
 set as-path prepend 65000 65000
exit
!
end
