frr defaults traditional
hostname fastweb
service integrated-vtysh-config
!
interface eth1
 ip address 10.200.0.11/24
exit
!
interface eth2
 ip address 10.100.5.0/31
exit
!
ip prefix-list OWN seq 5 permit 198.18.1.0/24
!
route-map OWN-ONLY permit 10
 match ip address prefix-list OWN
exit
!
router bgp 65401
 bgp router-id 10.200.0.11
 no bgp ebgp-requires-policy
 neighbor 10.200.0.1 remote-as 65300
 neighbor 10.200.0.1 timers connect 5
 no neighbor 10.200.0.1 enforce-first-as
 neighbor 10.100.5.1 remote-as 65200
 neighbor 10.100.5.1 timers connect 5
 !
 address-family ipv4 unicast
  network 198.18.1.0/24
  neighbor 10.200.0.1 route-map OWN-ONLY out
  neighbor 10.100.5.1 route-map OWN-ONLY out
 exit-address-family
exit
!
