frr defaults traditional
hostname internet
service integrated-vtysh-config
!
interface eth1
 ip address 10.100.3.1/31
exit
!
interface eth2
 ip address 10.100.4.1/31
exit
!
router bgp 65200
 bgp router-id 10.100.3.1
 no bgp ebgp-requires-policy
 neighbor 10.100.3.0 remote-as 65101
 neighbor 10.100.3.0 timers connect 5
 neighbor 10.100.4.0 remote-as 65102
 neighbor 10.100.4.0 timers connect 5
 !
 address-family ipv4 unicast
  network 198.51.100.0/24
  network 203.0.113.0/24
 exit-address-family
exit
!
