!
frr version 10.2.1_git
frr defaults traditional
hostname milan
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.0.0/31
 ip router isis CORE
 isis network point-to-point
exit
!
interface eth2
 ip address 10.0.0.7/31
 ip router isis CORE
 isis network point-to-point
exit
!
interface lo
 ip address 10.255.0.1/32
 ip router isis CORE
 isis passive
exit
!
router isis CORE
 is-type level-2-only
 net 49.0001.0102.5500.0001.00
 lsp-gen-interval 1
 spf-interval 1
exit
!
router bgp 65000
 bgp router-id 10.255.0.1
 neighbor RR peer-group
 neighbor RR remote-as 65000
 neighbor RR update-source 10.255.0.1
 neighbor RR timers connect 5
 neighbor 10.255.0.11 peer-group RR
 neighbor 10.255.0.12 peer-group RR
 !
 address-family ipv4 unicast
  network 192.0.2.0/26
  neighbor RR activate
 exit-address-family
exit
!
interface eth3
 ip address 10.0.0.8/31
 ip router isis CORE
 isis network point-to-point
exit
!
interface eth4
 ip address 10.0.0.12/31
 ip router isis CORE
 isis network point-to-point
exit
!
router isis CORE
 segment-routing on
 segment-routing global-block 16000 23999
 segment-routing prefix 10.255.0.1/32 index 1
exit
!
no zebra nexthop kernel enable
!
interface eth2
 isis metric 15
exit
!
