frr defaults traditional
hostname rr2
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.0.11/31
 ip router isis CORE
 isis network point-to-point
exit
!
interface lo
 ip address 10.255.0.12/32
 ip router isis CORE
 isis passive
exit
!
router isis CORE
 is-type level-2-only
 net 49.0001.0102.5500.0012.00
 lsp-gen-interval 1
 spf-interval 1
 set-overload-bit
exit
!
router bgp 65000
 bgp router-id 10.255.0.12
 neighbor CLIENTS peer-group
 neighbor CLIENTS remote-as 65000
 neighbor CLIENTS update-source 10.255.0.12
 neighbor CLIENTS timers connect 5
 neighbor 10.255.0.1 peer-group CLIENTS
 neighbor 10.255.0.2 peer-group CLIENTS
 neighbor 10.255.0.3 peer-group CLIENTS
 neighbor 10.255.0.4 peer-group CLIENTS
 neighbor 10.255.0.5 peer-group CLIENTS
 neighbor 10.255.0.6 peer-group CLIENTS
 neighbor 10.255.0.11 remote-as 65000
 neighbor 10.255.0.11 update-source 10.255.0.12
 neighbor 10.255.0.11 timers connect 5
 !
 address-family ipv4 unicast
  neighbor CLIENTS activate
  neighbor CLIENTS route-reflector-client
  neighbor 10.255.0.11 activate
 exit-address-family
exit
!
router isis CORE
 segment-routing on
 segment-routing global-block 16000 23999
 segment-routing prefix 10.255.0.12/32 index 12
exit
!
no zebra nexthop kernel enable
!
bfd
 profile FAST
  detect-multiplier 3
  receive-interval 100
  transmit-interval 100
 exit
exit
!
interface eth1
 isis bfd
 isis bfd profile FAST
exit
!
