frr defaults traditional
hostname rs
service integrated-vtysh-config
!
interface eth1
 ip address 10.200.0.1/24
exit
!
router bgp 65300
 bgp router-id 10.200.0.1
 no bgp ebgp-requires-policy
 neighbor MEMBERS peer-group
 neighbor MEMBERS timers connect 5
 neighbor 10.200.0.2 remote-as 65000
 neighbor 10.200.0.2 peer-group MEMBERS
 neighbor 10.200.0.11 remote-as 65401
 neighbor 10.200.0.11 peer-group MEMBERS
 neighbor 10.200.0.12 remote-as 65402
 neighbor 10.200.0.12 peer-group MEMBERS
 !
 address-family ipv4 unicast
  neighbor MEMBERS activate
  neighbor MEMBERS route-server-client
 exit-address-family
exit
!
