server:
  interface: 192.0.2.53
  access-control: 0.0.0.0/0 refuse
  access-control: 192.0.2.0/24 allow
  access-control: 100.64.0.0/10 allow
  access-control: 10.0.0.0/8 allow
  do-ip6: no
  username: ""
  chroot: ""
  use-syslog: no
  local-zone: "." static
  local-zone: "lab." static
  local-data: "web.internet.lab. A 198.51.100.1"
  local-data: "fastweb.lab. A 198.18.1.1"
  local-data: "netflix.lab. A 198.18.2.1"
  local-data: "whoami.lab. A 10.255.0.9"
